config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :mortuaries do
    resources :deceaseds
  end

  resources :deceaseds do
    resources :funerals
  end
end

app/models/funeral.rb
class Funeral < ApplicationRecord
  validates_presence_of :location, :time, :date
  belongs_to :deceased
  
end

app/controllers/funerals_controller.rb
class FuneralsController < ApplicationController
  before_action :set_deceased
  before_action :set_funeral, only: [:show, :edit, :update, :destroy]

def index
  @body_class = 'funeral-img'
  @title = 'Funerals'
  @funerals = @deceased.funeral
  flash[:info] = "This is Deceased's Funeral"
end

def show
  @body_class = 'funeral-img'
  @title = 'Funeral'
end

def new
  @body_class = 'funeral-img'
  @title = 'Add Funeral'
  @funeral = Funeral.new
end

def create
  @funeral = Funeral.new(funeral_params)
  @funeral.deceased_id = @deceased.id
    if @funeral.save
      flash[:success] = 'New Funeral Created'
      redirect_to deceased_funeral_path(@deceased, @funeral)
    else
      flash[:error] = 'Please Try Again'
      render :new
    end
end

def edit
  @body_class = 'funeral-img'
  @title = 'Edit Funeral'
end

def update
  if @funeral.update(funeral_params)
    flash[:success] = 'Funeral Updated'
    redirect_to deceased_funeral_path(@deceased, @funeral)
  else
    flash[:error] = 'Please Try Again'
    render :edit
  end
end

def destroy
  @funeral.destroy
  redirect_to deceased_funerals_path(@deceased)
end

private
  def funeral_params
    params.require(:funeral).permit(:location, :date, :time, :deceased_id)
  end

  def set_deceased
    @deceased = Deceased.find(params[:deceased_id])
  end

  def set_funeral
    @funeral = @deceased.funeral
  end
end

app/helpers/funerals_helper.rb
module FuneralsHelper
end

app/views/funerals/_form.html.erb
<%= form_for [@deceased, @funeral] do |f| %>
  <div class='field'>
    <div class='card'>
      <h3><%= f.label 'location', autofocus: true %></h3>
      <h5><%= f.text_field :location %></h5>
    </div><br />
    
    <div class='card'>
      <h3><%= f.label :time %></h3>
      <h5><%= f.time_field :time %></h5>
    </div><br />

    <div class='card'>
      <h3><%= f.label :date %></h3>
      <h5><%= f.date_field :date %></h5>
    </div><br />


  </div>

  <%= f.submit 'Submit', class: 'btn grey darken-2' %>
<% end %>

app/views/funerals/edit.html.erb
<h1>Edit Funeral Info</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', :back, class: 'btn grey darken-2' %>

app/views/funerals/index.html.erb
<h1>The Funeral</h1>

<div class='field'>
  <% if @funerals.nil? %>
    <h4>There is no funeral. Please add it.</h4>
  <% else %>
    <% @funerals.each do |funeral| %>
      <div class='col s12 m3'>
        <h5><%= funeral.location %> Funeral</h5>
        <%= link_to 'Show', deceased_funeral_path(@deceased, funeral), class: 'btn' %>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to 'New Funeral', new_deceased_funeral_path(@deceased), class: 'btn grey darken-2' %>

app/views/funerals/new.html.erb
<h1>Set New Funeral</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', :back, class: 'btn grey darken-2' %>

app/views/funerals/show.html.erb
<h1>The Funeral</h1>

<ul>
  <h3 class='field'>
    <div class=''>
      <li>Name: <%= @funeral.location %> </li>
    </div>
  </h3>
    <li>
      <%= link_to 'Edit', edit_deceased_funeral_path(@deceased, @funeral), class: 'btn grey darken-2' %>
      <%= link_to 'Delete', deceased_funeral_path(@deceased, @funeral), method: :delete, data: {confirm: 'Really Delete?'}, class: 'btn grey darken-2' %>
    </li>
</ul>

<%= link_to 'Back', :back, class: 'btn grey darken-2' %>
<%= link_to 'Funeral Home', deceased_funerals_path(@deceased), class: 'btn grey darken-2' %>