config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :mortuaries do
    resources :deceaseds
  end

  resources :deceaseds do
    resources :funerals
  end
end

app/models/mortuary.rb
class Mortuary < ApplicationRecord
  validates_presence_of :name, :city, :state

  belongs_to :user
  has_many :deceaseds
end

app/controllers/mortuaries_controller.rb
class MortuariesController < ApplicationController
  before_action :set_mortuary, only: [:show, :edit, :update, :destroy]
  def index
    @body_class = 'mortuary-img'
    @title = 'These are the Mortuaries'
    @mortuaries = current_user.mortuaries.paginate(page: params[:page], per_page: 5)
    flash[:info] = 'Welcome to Mortuaries'
  end

  def show
    @body_class = 'mortuary-img'
    @title = @mortuary.name
  end

  def new
    @body_class = 'mortuary-img'
    @title = 'Add New Mortuary'
    @mortuary = Mortuary.new
  end

  def create
    @mortuary = current_user.mortuaries.new(mortuary_params)
    if @mortuary.save
      flash[:success] = 'Mortuary Created'
      redirect_to mortuary_path(@mortuary)
    else
      flash[:error] = 'Please Try again'
      render :new
    end
  end

  def edit
    @body_class = 'mortuary-img'
    @title = 'Edit Mortuary'
  end

  def update
    if @mortuary.update(mortuary_params)
      flash[:success] = 'Morturary updated'
      redirect_to mortuary_path(@mortuary)
    else
      flash[:error] = 'Please Try again'
      render :edit
    end
  end

  def destroy
    @mortury.destroy(mortuary_params)
    flash[:success] = 'Mortuary Deleted'
    redirect_to mortuaries_path
  end

  private
    def set_mortuary
      @mortuary = Mortuary.find(params[:id])
    end

    def mortuary_params
      params.require(:mortuary).permit(:name, :city, :state)
    end
end

app/helpers/mortuaries_helper.rb
module MortuariesHelper
end

app/views/mortuaries/_form.html.erb
<%= form_for @mortuary do |f| %>
  <div class='field'>
    <div class='card'>
      <h3><%= f.label :name, autofocus: true %></h3>
      <h5><%= f.text_field :name %></h5>
    </div><br />
    
    <div class='card'>
      <h3><%= f.label :city %></h3>
      <h5><%= f.text_field :city %></h5>
    </div><br />

    <div class='card'>
      <h3><%= f.label :state %></h3>
      <h5><%= f.text_field :state %></h5>
    </div><br />
  </div>

  <%= f.submit 'Submit', class: 'btn grey darken-2'%>
<% end %>

app/views/mortuaries/edit.html.erb
<h1>Please Edit Mortuary</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', :back, class: 'btn grey darken-2' %>

app/views/mortuaries/index.html.erb
<h1>The Mortuaries</h1>

<div class='field'>
  <% if @mortuaries.any? %>
    <% @mortuaries.each do |mortuary| %>
      <div class='col s12 m3'>
        <h5><%= mortuary.name %></h5>
        <%= link_to 'Show', mortuary_path(mortuary), class: 'btn grey darken-2' %>
        <%= link_to 'The Deceased', mortuary_deceaseds_path(mortuary), class: 'btn grey darken-2' %>
      </div>
    <% end %>
  <% else %>
    <h4>There are no mortuaries. Please add one.</h4>
  <% end %>
</div>

<%= link_to 'New Mortuary', new_mortuary_path, class: 'btn grey darken-2 margin' %>

<div class=''>
  <%= will_paginate @mortuary %>
</div>

app/views/mortuaries/new.html.erb
<h1>Please Add a New Mortuary</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', :back, class: 'btn grey darken-2' %>

app/views/mortuaries/show.html.erb
<h1>The Mortuary</h1>

<ul>
  <h3 class='field'>
    <div class=''>
      <li>Name: <%= @mortuary.name %> </li>
    </div>
  </h3>
    <li>
      <%= link_to 'Edit', edit_mortuary_path(@mortuary), class: 'btn grey darken-2' %>
      <%= link_to 'Delete', mortuary_path(@mortuary), method: :delete, data: {confirm: 'Really Delete?'}, class: 'btn grey darken-2' %>
    </li>
</ul>

<%= link_to 'Back', :back, class: 'btn grey darken-2' %>
<%= link_to 'Deceased Home', mortuary_deceaseds_path(@mortuary), class: 'btn grey darken-2' %>