config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :mortuaries do
    resources :deceaseds
  end

  resources :deceaseds do
    resources :funerals
  end
end

app/models/deceased.rb
class Deceased < ApplicationRecord
  validates_presence_of :first_name, :last_name, :birthdate, :deathdate, :cod

  belongs_to :mortuary
  has_one :funeral

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/deceaseds_controller.rb
class DeceasedsController < ApplicationController
  before_action :set_mortuary
  before_action :set_deceased, only: [:show, :edit, :update, :destroy]

def index
  @body_class = 'deceased-img'
  @title = 'Deceased'
  @deceaseds = @mortuary.deceaseds.paginate(page: params[:page], per_page: 6)
  flash[:info] = "These are the Deceased"
end

def show
  @body_class = 'deceased-img'
  @title = @deceased.funeral
end

def new
  @body_class = 'deceased-img'
  @title = 'Add New Deceased'
  @deceased = Deceased.new
end

def create
  @deceased = @mortuary.deceaseds.new(deceased_params)
    if @deceased.save
      flash[:success] = 'New Deceased Created'
      redirect_to mortuary_deceased_path(@mortuary, @deceased)
    else
      flash[:error] = 'Please Try Again'
      render :new
    end
end

def edit
  @body_class = 'deceased-img'
  @title = 'Edit This Person'
end

def update
  if @deceased.update(deceased_params)
    flash[:success] = 'Deceased Updated'
    redirect_to mortuary_deceased_path(@mortuary, @deceased)
  else
    flash[:error] = 'Please Try Again'
    render :edit
  end
end

def destroy
  @deceased.destroy
  redirect_to mortuary_deceaseds_path(@mortuary)
end

private
  def deceased_params
    params.require(:deceased).permit(:first_name, :last_name, :birthdate, :deathdate, :cod, :mortruay_id)
  end

  def set_mortuary
    @mortuary = Mortuary.find(params[:mortuary_id])
  end

  def set_deceased
    @deceased = @mortuary.deceaseds.find(params[:id])
  end
end

app/helpers/deceaseds_helper.rb
module DeceasedsHelper
end

app/views/deceaseds/_form.html.erb
<%= form_for [@mortuary, @deceased] do |f| %>
  <div class='field'>
    <div class='card'>
      <h3><%= f.label 'first name', autofocus: true %></h3>
      <h5><%= f.text_field :first_name %></h5>
    </div><br />
    
    <div class='card'>
      <h3><%= f.label :last_name %></h3>
      <h5><%= f.text_field :last_name %></h5>
    </div><br />

    <div class='card'>
      <h3><%= f.label :birthdate %></h3>
      <h5><%= f.date_field :birthdate %></h5>
    </div><br />

    <div class='card'>
      <h3><%= f.label :deathdate %></h3>
      <h5><%= f.date_field :deathdate %></h5>
    </div><br />

    <div class='card'>
      <h3><%= f.label :cod %></h3>
      <h5><%= f.text_area :cod %></h5>
    </div><br />
  </div>

  <%= f.submit 'Submit', class: 'btn grey darken-2' %>
<% end %>

app/views/deceaseds/edit.html.erb
<h1>Edit Deceased</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', :back, class: 'btn grey darken-2' %>

app/views/deceaseds/index.html.erb
<h1 class="center">The Deceased</h3>
<br />

  <div class="row">
    <% if @deceaseds.any? %>
      <% @deceaseds.each do |deceased| %>
        <div class="col s12 m6">
          <div class="z-depth-5">
            <div class="card stones">
              <div class="card-content">
                <span class="card-title black-text"><%= deceased.birthdate %>___________
                                                    <%= deceased.deathdate %> 
                </span><br />
                <span class="card-title black-text"><%= deceased.full_name %></span><br />
                <span class="card-title black-text"><h3>Died Doing What They Loved</h3></span>
                <span class="card-title black-text"><%= deceased.cod %>
              </div>
            </div>
          </div>
         <%= link_to 'Show', mortuary_deceased_path(@mortuary, deceased), class: 'btn grey darken-2' %>
        </div>
      <% end %>
    <% else %>
      <h4>There are no deceased </h4>
    <% end %>
  </div>

<%= link_to 'Back', :back, class: 'btn grey darken-2' %>
<%= link_to 'Add New Deceased', new_mortuary_deceased_path(@mortuary), class: 'btn grey darken-2' %>

app/views/deceaseds/new.html.erb
<h1>Enter Deceased</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', :back, class: 'btn grey darken-2' %>

app/views/deceaseds/show.html.erb
<h1 class="center">The Deceased</h3>
<br />
  <div class="row">
        <div class="col s12">
          <div class="z-depth-5">
            <div class="card stones">
              <div class="card-content">
                <span class="card-title black-text"><%= @deceased.birthdate %>___________________
                                                    <%= @deceased.deathdate %> 
                </span><br />
                <span class="card-title black-text"><%= @deceased.full_name %></span><br />
                <span class="card-title black-text"><h3>Died Doing What They Loved</h3></span>
                <span class="card-title black-text"><%= @deceased.cod %>
              </div>
            </div>
          </div>
  </div>
   <%= link_to 'Edit', edit_mortuary_deceased_path(@mortuary, @deceased), class: 'btn grey darken-2' %>
   <%= link_to 'Delete', mortuary_deceased_path(@mortuary, @deceased), method: :delete, 
                    data: {confirm: 'Really Delete?'}, class: 'btn grey darken-2' %>
</div>

<%= link_to 'Back', :back, class: 'btn grey darken-2' %>

<%= link_to 'Funeral', deceased_funerals_path(@deceased), class: 'btn grey darken-2' %>

<%= link_to 'Deceased Home', mortuary_deceaseds_path(@mortuary), class: 'btn grey darken-2' %>