config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :mortuaries do
    resources :deceaseds
  end

  resources :deceaseds do
    resources :funerals
  end
end

app/views/layouts/_navbar.html.erb
<nav class='grey darken-3'>
  <div class='nav-wrapper'>
    <h1 class='brand-logo'><%= @title if @title %></h1>
    <a href="#!" class="brand-logo"></a>
    <a href="#" data-activates="mobile" class="button-collapse">
      <i class="fa fa-bars"></i>
    </a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to 'Home', :root %></li>
      <li><%= link_to 'Morturaries Home', mortuaries_path %></li>
      <% if user_signed_in? %>
        <li>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="active">
          <%= link_to 'Login', new_user_session_path %>
        </li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile">
      <li><%= link_to 'Home', :root %></li>
      <li><%= link_to 'Mortuaries Home', mortuaries_path %></li>
      <% if user_signed_in? %>
        <li>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
      <li class="active">
        <%= link_to 'Login', new_user_session_path %>
      </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FurneralDirector</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= @body_class %>">
    <%= render 'layouts/navbar' %>
    
    <% flash.each do |type, message| %>
      <div class='flash <%= type %>'>
        <%= message %>
      </div>
    <% end %>

    <div class='container center'>
    <%= yield %>
    </div>
  </body>
</html>